@startuml content-interaction
[*] --> CONTENT_INTERACTION

state FILTER_CONTENT {
    state R1 as " "    
    state R2 as " "
    [*] --> R1
    R1 --> R2    
    note on link
        <b> System allows to:</b>
        * Filter article by category        
        * Filter article by state        
    end note
    R2 --> [*]
}

state SEARCH_CONTENT {
    state S1 as " "    
    state S2 as " "
    [*] --> S1
    S1 --> S2    
    note on link
        <b> System allows to:</b>
        * Search content by title         
    end note
    S2 --> [*]
}

state VIEW_ARTICLE {
    state V1 as " "    
    state V2 as " "
    state V3 as " "    
    [*] --> V1
    V1 --> V2 

    state addProposedOrNot <<choice>>
           
    note on link
        <b> System show:</b>
        * View content details
            * title
            * description
            * date of publication
            * quantity of proposals
            * user who published
            * gallery
    end note
    V2 --> V3    
    note on link
        <b> System allows to:</b>
        * Select a published 
            article to proposed
    end note 

    V3 --> addProposedOrNot    
    addProposedOrNot -[#red]-> V2
    note on link
        <b> System requires:</b>
        * Must have a published 
            article to proposed
    end note 
    addProposedOrNot --> [*]
}

CONTENT_INTERACTION --> FILTER_CONTENT
CONTENT_INTERACTION --> SEARCH_CONTENT

state union <<choice>> 

FILTER_CONTENT --> union
SEARCH_CONTENT --> union
union --> VIEW_ARTICLE

state finished <<choice>>

VIEW_ARTICLE --> finished
finished --> [*]
finished --> CONTENT_INTERACTION

@enduml