@startuml architecture-analysis

package vistas {
    boundary AutenticacionVista    
    boundary EditarPerfilVista
    boundary ArticuloVista
    boundary PublicacionVista    
    boundary CalificacionVista
    boundary IntercambioVista    
}
package controladores {
    control AutenticacionControlador
    control UsuarioControlador    
    control ArticuloControlador    
    control CalificacionControlador
    control IntercambioControlador        
}
skinparam roundcorner 20

package modelos {
    entity Usuario
    entity Articulo
    entity Intercambio
    entity Calificacion          
}
skinparam Dpi 500

vistas ..> modelos
vistas ..> controladores
controladores ..> modelos

@enduml