@startuml profile-management 

[*] --> PROFILE_MANAGEMENT

state EDIT_PROFILE {
    state EPS1 as " "
    state EPS2 as " "
    state EPC1 <<choice>>

    [*] --> EPS1

    EPS1 --> EPS2
    note on link
        <b> System allows edit to: </b>        
        * Profile picture
        * Description
        * Number of WhatsApp
    end note
    
    EPS2 --> EPC1
    ' note on link 
    '     <b> User provides requested </b>        
    ' end note

    EPC1 -[#red]--> EPS1
    note on link
        <b> System requires: </b>
        * Profile picture not empty
        * Description not empty 
        * Valid WhatsApp number
    end note

    EPC1 --> [*]
    note on link
        <b> System allows: </b>
        * Edit profile
    end note
}

PROFILE_MANAGEMENT --> EDIT_PROFILE

state union <<choice>>
EDIT_PROFILE --> union
union --> [*]
union --> PROFILE_MANAGEMENT
@enduml