@startuml content-interaction
[*] --> INTERACCION_CONTENIDO

skinparam linetype polyline
skinparam Dpi 500

state FILTRAR_ARTICULOS {
    state FAS1 as " "    
    state FAS2 as " "
    [*] --> FAS1
    FAS1 --> FAS2    
    note on link
        <b> El sistema permite:</b>
        * Filtrar artículos por categoría
        * Filtrar artículos por estado
    end note
    FAS2 --> [*]
}

state BUSCAR_ARTICULO {
    state S1 as " "    
    state S2 as " "
    [*] --> S1
    S1 --> S2    
    note on link
        <b> El sistema permite:</b>
        * Buscar artículos por título
    end note
    S2 --> [*]
}

state VER_ARTICULO {
    state VAS1 as " "
    state VAS2 as " "
    state VAS3 as " "
    state VAS4 as " "
    state VAS5 as " "
    state VAS6 as " "
    [*] --> VAS1
    VAS1 --> VAS2 

    state checkPublications <<choice>>           
    state addProposedOrNot <<choice>>
    state addProposedOrAccepExchange <<choice>>
    note on link
        <b> El sistema muestra:</b>
        * Ver detalles del artículo
            * título
            * descripción
            * fecha de publicación
            * cantidad de propuestas
            * publicador
            * galería
            * proponer artículo
    end note
        
    VAS2 --> addProposedOrAccepExchange
    note on link
        <b> El sistema permite:</b>
        * Proponer artículo
        * Aceptar intercambio
    end note

    addProposedOrAccepExchange --> VAS3
    note on link
        <b> El sistema permite:</b>
        * Proponer artículo                    
    end note
    
    VAS3 --> VAS4    
    note on link
        <b> El sistema permite:</b>
        * Seleccionar un artículo
         publicado para proponer
    end note 

    VAS4 --> checkPublications    
    checkPublications -[#red]-> VAS3
    note on link
        <b> El sistema requiere:</b>
        * Tener un artículo
         publicado para proponer
        * No se puede proponer
         un mismo artículo
    end note 


    addProposedOrAccepExchange --> VAS5
    note on link
        <b> El sistema permite:</b>
        * Aceptar intercambio
    end note

    VAS5 --> VAS6
    note on link
        <b> El sistema permite:</b>
        * Aceptar intercambio
        * Contactar por whatsapp
    end note

    VAS6 --> addProposedOrNot
    addProposedOrNot -[#red]-> VAS5
    note on link
        <b> El sistema requiere:</b>
        * No tener un intercambio 
        aceptado para el mismo 
        articulo
    end note

    addProposedOrNot --> [*]   
    checkPublications --> [*]        
}

state INTERCAMBIAR_ARTICULO {
    state EAS1 as " "    
    state EAS2 as " "
    state EAS3 as " "    
    state EAS4 as " "                   
    [*] --> EAS1
    
    state ratingOrDiscard <<choice>>

    EAS1 --> EAS2
    note on link
        <b> El sistema muestra:</b>
        * Listado de intercambios 
            aceptados
        * Calificar intercambio
        * Descartar intercambio        
    end note
      
    EAS2 --> ratingOrDiscard
    ratingOrDiscard --> EAS4
    note on link
        <b> El sistema permite:</b>
        * Calificar intercambio
            * Puntuación del 1 a 5
            * Comentario            
    end note

    ratingOrDiscard --> EAS3
    note on link
        <b> El sistema permite:</b>
        * Descartar intercambio
    end note

    EAS3 --> [*]    
    EAS4 --> [*]    

}

INTERACCION_CONTENIDO -right-> FILTRAR_ARTICULOS
INTERACCION_CONTENIDO -left-> BUSCAR_ARTICULO
INTERACCION_CONTENIDO --> INTERCAMBIAR_ARTICULO

state union <<choice>> 

FILTRAR_ARTICULOS --> union
BUSCAR_ARTICULO --> union
union --> VER_ARTICULO

state finished <<choice>>
INTERCAMBIAR_ARTICULO --> finished
VER_ARTICULO --> finished
finished --> [*]
finished --> INTERACCION_CONTENIDO

@enduml

' Describe este diagrama 'Diagrama de estados y actividad para la interacción con el contenido'

Mediante este diagrama se puede observar la interacción del usuario con el contenido de la aplicación. El usuario puede filtrar artículos por categoría y estado, buscar artículos por título, ver detalles del artículo, proponer artículo, aceptar intercambio, contactar por whatsapp, calificar intercambio y descartar intercambio, asimismo, lo que el sistema muestra, permite y requiere.