@startuml use-cases-context
skinparam Dpi 1000
skinparam linetype polyline

[*] --> AUTENTICACION

AUTENTICACION --> UNIMART_ABIERTO: Inciar Sesión
UNIMART_ABIERTO --> INTERACCION_CONTENIDO
UNIMART_ABIERTO --> GESTION_PERFIL

INTERACCION_CONTENIDO --> INTERACCION_CONTENIDO
note on link
  * Ver artículos
  * Publicar artículos
  * Buscar y filtrar artículos
  * Proponer artículos    
end note

UNIMART_ABIERTO --> INTERCAMBIOS

INTERCAMBIOS --> INTERCAMBIOS
note on link
  * Ver intercambios
  * Aceptar intercambios
  * Descartar intercambios
end note

GESTION_PERFIL --> GESTION_PERFIL
note on link
  * Editar perfil
end note

state logout <<choice>>


INTERACCION_CONTENIDO --> logout: Cerrar sesión
INTERCAMBIOS --> logout: Cerrar sesión

GESTION_PERFIL --> logout: Cerrar sesión

UNIMART_ABIERTO --> logout: Cerrar sesión
logout --> [*]: Cerrar sesión
logout -left-> UNIMART_ABIERTO: Iniciar sesión
@enduml